language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script:
  - chmod +x ./gradlew build connectedCheck